In [1]:
from numpy import array, zeros
import numpy as np
import matplotlib.pyplot as plt
from scipy.misc import derivative

Questão 2: Sistema Linear

In [2]:
def LU_Decomposition_method(A, b):  # cria-se a função do método
    m = len(A)
    y = np.zeros(m)
    x = np.zeros(m)
    U = A
    L = np.zeros([m, m])
    for k in range(0, m):
        for r in range(0, m):
            if (k == r):
                L[k, r] = 1
            if (k < r):
                factor = (A[r, k]/A[k, k])
                L[r, k] = factor
                for c in range(0, m):
                    U[r, c] = A[r, c] - (factor * A[k, c])
    A = np.zeros([m, m])
    for r in range(0, m):
        for c in range(0, m):
            for k in range(0, m):
                A[r, c] += (L[r, k] * U[k, c])
    print('A')
    print(A)
    print('L')
    print(L)
    print()
    print('U')
    print(U)
    # RESOLUÇÃO DAS EQUAÇÕES MATRICIAIS
    ###################################
    y = np.linalg.solve(L, b)
    x = np.linalg.solve(U, y)
    ###################################
    f = 'SOLUÇÃO DO SISTEMA'
    print('-'*(len(f)+32))
    print(f'{f:^50}')
    print('-'*(len(f)+32))
    print('x =')
    print(x)
    print('Onde: ')
    for c in range(0, len(x)):
        print(f'\t x[{c}] = {x[c]} \n')
    return x

In [3]:
A = np.array([[1, 1, 1, 2],
              [2, 1, 0, 2],
              [0, 1, 1, 1],
              [2, 0, 1, 2]])
b = np.transpose([25, 25, 15, 25])
Res=LU_Decomposition_method(A,b)

A
[[1. 1. 1. 2.]
 [2. 1. 0. 2.]
 [0. 1. 1. 1.]
 [2. 0. 1. 2.]]
L
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 2.  2. -3.  1.]]

U
[[ 1  1  1  2]
 [ 0 -1 -2 -2]
 [ 0  0 -1 -1]
 [ 0  0  0 -1]]
--------------------------------------------------
                SOLUÇÃO DO SISTEMA                
--------------------------------------------------
x =
[5. 5. 5. 5.]
Onde: 
	 x[0] = 5.0 

	 x[1] = 5.0 

	 x[2] = 5.0 

	 x[3] = 5.0 



Questão 3: Problema de raízes

In [4]:
def F(x) : 
    return x*x - 4*x + 2
def d(x): #função da derivada de F no ponto x
    return derivative(F, x)

def newtonraphson(xi,TOL, iter=100):
    i = 0
    e=100
    while abs(e) >= TOL and i<iter:
        x0=xi
        xi=xi-F(xi)/d(xi) # X(i++) = x(i) - f(x(i))/d(f(x(i)))
        e=abs(((xi - x0)/xi))*100 
        i=i+1
        print("Iteração: %d \n Xi: %f \n F(xi): %f \n Ea: %f" % (i, xi, F(xi), e))
    return{"x": xi, "i": i} 

In [5]:
# Letra A - x0 = 3
newtonraphson(3,0.01) 

Iteração: 1 
 Xi: 3.500000 
 F(xi): 0.250000 
 Ea: 14.285714
Iteração: 2 
 Xi: 3.416667 
 F(xi): 0.006944 
 Ea: 2.439024
Iteração: 3 
 Xi: 3.414216 
 F(xi): 0.000006 
 Ea: 0.071788
Iteração: 4 
 Xi: 3.414214 
 F(xi): 0.000000 
 Ea: 0.000062


{'x': 3.4142135623746896, 'i': 4}

In [6]:
# Letra B - x0 = -3
newtonraphson(-3,0.01) 

Iteração: 1 
 Xi: -0.700000 
 F(xi): 5.290000 
 Ea: 328.571429
Iteração: 2 
 Xi: 0.279630 
 F(xi): 0.959674 
 Ea: 350.331126
Iteração: 3 
 Xi: 0.558545 
 F(xi): 0.077794 
 Ea: 49.936028
Iteração: 4 
 Xi: 0.585529 
 F(xi): 0.000728 
 Ea: 4.608548
Iteração: 5 
 Xi: 0.585786 
 F(xi): 0.000000 
 Ea: 0.043940
Iteração: 6 
 Xi: 0.585786 
 F(xi): 0.000000 
 Ea: 0.000004


{'x': 0.5857864376269047, 'i': 6}

Questão 4: Gauss-Siedel

In [7]:
def seidel(a, x ,b):
    #Finding length of a(2) 
    maxit = 10
    es=0.05
    iter = 0
    n = len(a)
    x0 = zeros(n)
    er = zeros(n)
    # for loop for 3 times as to calculate x, y , z

    while True:
        for j in range(0, n):        
            # temp variable d to store b[j]
            d = b[j]                  
          
            # to calculate respective xi, yi, zi
            for i in range(0, n):     
                if(j != i):
                    d-=a[j][i] * x[i]
            # updating the value of our solution
                    x0[j] = x[j]
                    x[j] = d / a[j][j]
                    if x[j] != 0:
                        er[j] = abs((x[j] - x0[j])/x[j])*100
                        print(f'x= {x}')
                        print(f'xv= {x0}')
                        print(f'erro = {er}')
        # returning our updated solution  
        iter = iter+1
        print(f'iteração = {iter}')
        if max(er)<=es or iter >= maxit:
            break
    print(f'Com {iter} iterações: \n x = \n {x}')
    print(f'erro = {er}')

In [8]:
A = array([[35, -10],
           [-10, 40]])
b = array([200, 0])
x = [0, 0] 


seidel(A,x,b)

x= [5.714285714285714, 0]
xv= [0. 0.]
erro = [100.   0.]
x= [5.714285714285714, 1.4285714285714286]
xv= [0. 0.]
erro = [100. 100.]
iteração = 1
x= [6.122448979591836, 1.4285714285714286]
xv= [5.71428571 0.        ]
erro = [  6.66666667 100.        ]
x= [6.122448979591836, 1.530612244897959]
xv= [5.71428571 1.42857143]
erro = [6.66666667 6.66666667]
iteração = 2
x= [6.151603498542274, 1.530612244897959]
xv= [6.12244898 1.42857143]
erro = [0.47393365 6.66666667]
x= [6.151603498542274, 1.5379008746355685]
xv= [6.12244898 1.53061224]
erro = [0.47393365 0.47393365]
iteração = 3
x= [6.153685964181591, 1.5379008746355685]
xv= [6.1516035  1.53061224]
erro = [0.03384095 0.47393365]
x= [6.153685964181591, 1.5384214910453977]
xv= [6.1516035  1.53790087]
erro = [0.03384095 0.03384095]
iteração = 4
Com 4 iterações: 
 x = 
 [6.153685964181591, 1.5384214910453977]
erro = [0.03384095 0.03384095]


Questão 5: Newton-Raphson 

In [9]:
from math import pi, exp
from numpy import array, divide, linalg

x = [1, 1]

iter = 0
maxit = 500
es = 0.1
x0 = 100
while True:
    F = array([2*x[0] + 2*x[1]*x[0] - 10,
                  2*x[1] + 2*x[1]*x[0] - 10])      # Matriz de funções
    J = array([[2 + 2*x[1],    2*x[0]],
         [2*x[1], 2 + 2*x[0]]]) 
    dx = linalg.lstsq(J,F,rcond=None)[0]
    x0 = x
    x = x - dx
    iter += 1
    ea = abs((x-x0)/x)*100
    print(f'Com {iter} iterações:')
    print(f'Com erro: {ea} \n x = \n {x}')
    if iter >= maxit or max(ea) <= es:
        print(f'Com {iter} iterações: \n x = \n {x}')
        break

Com 1 iterações:
Com erro: [50. 50.] 
 x = 
 [2. 2.]
Com 2 iterações:
Com erro: [11.11111111 11.11111111] 
 x = 
 [1.8 1.8]
Com 3 iterações:
Com erro: [0.48543689 0.48543689] 
 x = 
 [1.79130435 1.79130435]
Com 4 iterações:
Com erro: [0.00092114 0.00092114] 
 x = 
 [1.79128785 1.79128785]
Com 4 iterações: 
 x = 
 [1.79128785 1.79128785]
